### ISSUE TITLE
include java version in system info

### ISSUE THREAD

**Issue by duncdrum** [wolfgangmm/monex#8]
![screen shot 2014-08-19 at 7 55 21 pm](https://cloud.githubusercontent.com/assets/6205362/3970435/5d756e50-27ca-11e4-856c-70a0376a7907.png)
Wouldn't it make sense to show the java version in system info box? Especially on mac os x with its competing java releases, i remember having to manually fiddle to make sure exist uses the right java. So having it all in one spot, might make for a little quality of live improvement.

**Comment by joewiz** [comment]
@duncdrum Nice idea! Would you consider filing a PR to add this? I believe it's accessible via:

```xquery
util:system-property("java.version")
```

The available system properties are documented at https://docs.oracle.com/javase/tutorial/essential/environment/sysprop.html

**Comment by duncdrum** [comment]
@joewiz, let me see what i can cook up

**Comment by duncdrum** [comment]
i couldn't figure out how to get it via jmx despite this [discussion](http://stackoverflow.com/questions/14246375/determine-java-version-through-jmx)
